### PR TITLE
fix: Ensure the swap liquidity is at min 10k sats

### LINKED ISSUE #721: Ensure swap liquidity is never less than miniumum swap size.
Currently the swap liquidity can be less than the minimum swap size (10k sats as our default). The maker will happily run.

Instead it should halt the process and prompt the user to add more liquidity in the logs.

### PR DESCRIPTION
**Pull request by 0xEgao**
Fixes #721, by enforcing the `MakerConfig` to not be initialized if the`minimum_swap_amount` is lesser than 10k sats, and by continuously checking the swap-liquidity at certain interval of time. 
Note-: The v1-maker server already checks for `swap_liquidity` at certain interval of time.

### CODE REVIEW

File: src/maker/server2.rs [hunk 1]
```diff
@@ -401,30 +401,50 @@ fn setup_fidelity_bond_taproot(
...
-    {
-        let mut wallet = maker.wallet().write()?;
-        wallet.refresh_offer_maxsize_cache()?;
-    }
-    let wallet_read = maker.wallet().read()?;
-    let balances = wallet_read.get_balances()?;
+    let sleep_incremental = 10;
+    let mut sleep_duration = 0;
+    while !maker.shutdown.load(Relaxed) {
+        {
```
Comment (mojoX911) [inline src/maker/server2.rs:409]: Is it not possible to unify the liquidity check for both protocols? The logic should be exactly the same.

File: src/maker/server2.rs [hunk 2]
```diff
@@ -401,30 +401,50 @@ fn setup_fidelity_bond_taproot(
...
+                .wallet()
+                .write()?
+                .get_next_external_address(AddressType::P2TR)?;
+            log::warn!(
+                "[{}] Low taproot swap liquidity | Min: {} sats | Available: {} sats | Fund: {}",
+                maker.config.network_port,
+                min_required,
+                offer_max_size,
+                funding_addr,
+            );
```
Comment (mojoX911) [inline src/maker/server2.rs:430]: We need to add a recving address here to recv more funds just like legacy server. 

Its cleaner to just have one impl and use it in both the protocols.

File: src/maker/config.rs [hunk 3]
```diff
@@ -67,6 +67,19 @@ impl Default for MakerConfig {
     }
 }
 
+fn validate_minimum_swap_amount(amount: u64) -> io::Result<u64> {
+    if amount < MIN_SWAP_AMOUNT {
+        log::error!(
+            "Configured min_swap_amount {} is below protocol minimum {} sats",
+            amount,
```
Comment (mojoX911) [inline src/maker/config.rs]: Inline this. This is a small one time use logic. Doesn't need a function.

**Review by mojoX911 — CHANGES_REQUESTED** [review]

File: src/maker/server2.rs (hunk 1 above)
Comment (0xEgao) [reply src/maker/server2.rs:409]: I didn't unified them because then I had to keep multiple parameters in function signature (probably creating a trait which both type of makers will impl), since both v1 and v2 maker structs are different.
As well another reason of not doing so was the ongoing unification of both v1 and v2 makers we gonna have soon.

Comment (mojoX911) [reply src/maker/server2.rs:409]: Hm Okay. In that case just make sure both the impls are following the same steps. We should not have missing steps.

Comment (0xEgao) [reply src/maker/server2.rs:409]: Sure

File: src/maker/config.rs (hunk 3 above)
Comment (0xEgao) [reply src/maker/config.rs]: Done

File: src/maker/server2.rs (hunk 2 above)
Comment (0xEgao) [reply src/maker/server2.rs:430]: Done

File: src/maker/server2.rs [hunk 4]
```diff
@@ -401,30 +401,48 @@ fn setup_fidelity_bond_taproot(
     ))
 }
 
-/// Checks swap liquidity for taproot swaps
+/// Blocks until sufficient liquidity is available for taproot swaps.
 fn check_swap_liquidity_taproot(maker: &Maker) -> Result<(), MakerError> {
```
Comment (mojoX911) [inline src/maker/server2.rs:405]: This at current stage, will not actually block the maker network thread if liquidity isn't enough. 

This routine is runing on a loop in a subthread. So if liquidity is low, it will just log, sleep, restart.

We need a mechanism to stop the main network thread, so makers don't respond to swap request until liquidity is restored.

Look inside the `check_connection_with_core` function. It has a global switch `rcp_ping_success`. And if thats false the main network listening thread pauses until the switch turns on again.

Same need to be done here. Its crucial to block the maker if liquidity is low. All swaps will fail, and user might not notice it in due time in an headless node.

Comment (mojoX911) [reply src/maker/server2.rs:405]: Ah i just noticed. `check_connection_with_core` in `server2` taproot, doesn't have the switch. It should be added there too. 

In general, any thread which is critical for swap process should have this switch. If anything goes wrong in these threads swaps should not be started.

Comment (mojoX911) [reply src/maker/server2.rs:405]: I think I am wrong. We had the switch before, but that had been removed at some point. Now the mechanism seems different. This routine is part of the main thread itself, not a sub-thread. So it should block the main thread if liquidity is low.

Lets add the IT for this to be absolutely sure.

Comment (0xEgao) [reply src/maker/server2.rs:405]: Added an IT, yes this blocks the thread until we fund the maker again.

Comment (mojoX911) [reply src/maker/server2.rs:405]: Let's play that behavior in IT then.

- Deplete the fund. Assert that warning logs are coming.
- Swap attempt will fail at that stage. Showing maker not responding to the offer request.
- Refund the maker, and assert that warning logs are gone and the maker is back online.
- Swap should pass at this stage.

Comment (mojoX911) [reply src/maker/server2.rs:405]: In the whole process, the maker server should not crash or throw any panic.

Comment (0xEgao) [reply src/maker/server2.rs:405]: Done, Added this behavior

File: tests/liquidity_test.rs [hunk 5]
```diff
@@ -0,0 +1,106 @@
...
+    fund_taproot_makers(&taproot_maker, bitcoind, 4, Amount::from_btc(0.05).unwrap());
+
+    // Attempt the swap again, it should succeed
+    match taproot_taker.do_coinswap(swap_params.clone()) {
+        Ok(Some(_report)) => {
+            log::info!("✅ Taproot coinswap completed successfully!");
+        }
+        Ok(None) => {
+            log::warn!("Taproot coinswap completed but no report generated (recovery occurred)");
+        }
```
Comment (mojoX911) [inline tests/liquidity_test.rs:103]: panic here..

Comment (mojoX911) [reply tests/liquidity_test.rs:103]: Also where exactly is the balance being depleted?

Comment (0xEgao) [reply tests/liquidity_test.rs]: The after swap balances?
I can assert them.

Comment (0xEgao) [reply tests/liquidity_test.rs:103]: The wallet is drained after doing `network bootstrap` when running maker server
