### PR TITLE
test: (V1) move balance verification to individual test cases

### LINKED ISSUE #671: V1 Integration Tests Fail Sporadically Due to Shared Balance Verification and Assertion's Overload
Some V1 integration test cases fail sporadically, even when the swap flow completes successfully according to the desired behaviour. These failures are mainly related to how balances are verified during test execution.

**Causes** :
1-)Balance verification is performed via a common/shared function with overloaded assertions covering multiple balance values, making it hard to determine which test or condition caused a failure.

2-)Fee workflow diagrams and related data are not up-to data with latest swap data.

**Approach to fix**:
1-)Update the fee workflow diagram using the generated swap report and align balance verification logic in test cases with this updated workflow.

2-)Move balance verification into individual test cases instead of relying on shared verification logic in `test_framework/mod.rs`, so each test validates only its own expected balances.

### PR DESCRIPTION
**Pull request by 0xEgao**
fixes #671

### CODE REVIEW

File: tests/standard_swap.rs [hunk 1]
```diff
@@ -108,36 +108,140 @@ fn test_standard_coinswap() {
...
+        let wallet = taker.get_wallet();
+        let balances = wallet.get_balances().unwrap();
+
+        // Debug logging for taker
+        log::info!(
+            "🔍 DEBUG Taker - Regular: {}, Swap: {}, Spendable: {}",
+            balances.regular.to_btc(),
+            balances.swap.to_btc(),
+            balances.spendable.to_btc()
+        );
```
Comment (mojoX911) [inline tests/standard_swap.rs:147]: Add contract balance too.

File: tests/standard_swap.rs [hunk 2]
```diff
@@ -108,36 +108,140 @@ fn test_standard_coinswap() {
...
+            "Taker swapcoin balance mismatch"
+        );
+
+        assert_in_range!(balances.contract.to_sat(), [0], "Contract balance mismatch");
+        assert_eq!(balances.fidelity, Amount::ZERO);
+
+        // Check balance difference
+        let balance_diff = org_taker_spend_balance
+            .checked_sub(balances.spendable)
+            .unwrap();
```
Comment (mojoX911) [inline tests/standard_swap.rs:170]: no checked_sub. Assert negative diffs too. Add comments on why makers make/loose money. Applies to all tests.

File: tests/abort1.rs [hunk 3]
```diff
@@ -130,41 +130,126 @@ fn test_stop_taker_after_setup() {
...
-    // +------------------+------------------------------------+---------------------+--------------------+----------------------------+
-    // | Participant      | Mining Fee for Contract txes (Sats) | Timelock Fee (Sats) | Funding Fee (Sats) | Total Recovery Fees (Sats) |
-    // +------------------+------------------------------------+---------------------+--------------------+----------------------------+
-    // | Taker            | 3,000                              | 768                 | 3,000             | 6,768                      |
-    // | Maker16102       | 3,000                              | 768                 | 3,000             | 6,768                      |
-    // | Maker6102        | 3,000                              | 768                 | 3,000             | 6,768                      |
-    // +------------------+------------------------------------+---------------------+--------------------+----------------------------+
-    //
+    // +------------------+------------------------------------+---------------+
+    // | Participant      |  Timelock Fee (Sats)  | Total Recovery Fees (Sats) |
```
Comment (mojoX911) [inline tests/abort1.rs]: No point in adding  `Total Recovery Fee` is its the same. Just have one column with `Timelock Recovery Fee`.

**Review by mojoX911 — CHANGES_REQUESTED** [review]

File: tests/malice2.rs [hunk 4]
```diff
@@ -155,31 +149,130 @@ fn malice2_maker_broadcast_contract_prematurely() {
...
-    // | **Taker**      | 3,000                              | 768                 | 3,000              | 6,768                      |
-    // | **Maker16102** | 3,000                              | 768                 | 3,000              | 6,768                      |
-    // | **Maker6102**  | 3,000                              | 768                 | 3,000              | 6,768                      |
+    // | Participant    | Mining Fee for Contract txes (Sats) |  Fee (Sats)         | Funding Fee (Sats)| Total Balance Diff (Sats)   |
+    // |----------------|------------------------------------|----------------------|--------------------|----------------------------|
+    // | **Taker**      | -                                  | 858 (Timelock)       | -                  | 858                        |
+    // | **Maker16102** | -                                  | 444,213(balance diff)| -                  | 444,213                    |
+    // | **Maker6102**  | -                                  | 466,498(balance diff)| -                  | 466,498                    |
```
Comment (mojoX911) [inline tests/malice2.rs]: Ohh these numbers are really high. Basically, makers are not recovering from swaps?

File: tests/abort1.rs (hunk 3 above)
Comment (mojoX911) [reply tests/abort1.rs]: Or even better show the full table with other columns empty as you have done for other tests.

File: tests/malice2.rs (hunk 4 above)
Comment (mojoX911) [reply tests/malice2.rs]: This is because the makers are being shut down. They should not stop. And the faulty maker should be started again. 

Then it will trigger recovery, and the correct balance will come. 

We should also watch and wait in the logs to check that recovery is completed before moving to balance verification.

Comment (mojoX911) [reply tests/malice2.rs]: This is, in general, true for all tests where we have changing maker behavior. Currently, changing behavior also shuts down the makers at a specific stage. 

For all such cases, those makers should be restarted again and asserted for post-collapse restart behaviors. Mostly, they will see some unfinished swaps and will try to recover from them. 

Our current tests have been incomplete in this regard for a long time. It never asserted restart behaviors. Let's fix all of that here.

File: tests/standard_swap.rs (hunk 2 above)
Comment (0xEgao) [reply tests/standard_swap.rs:170]: `checked_sub` helps us assert negative diffs, it's not like `saturating_sub` which results 0 if there is negative diffs. So currently `checked_sub` helps us asserts for negative diffs like giving us the diff when maker loosing after recovering via timelock.
Yeah i will add comments to this diff assertion whether and why maker has lost/gain some money here.

**Review by mojoX911 — APPROVED** [review]
Ack
