### PR TITLE
don't sweep when recovery needed

### LINKED ISSUE #564: Contract being broadcasted after sweeping.
In abort3_case3 situation we are trying to broadcast contract after sweeping resulting in bad-tx error.

```
2025-07-25T11:13:47.578132826+00:00 INFO coinswap::wallet::api - Sweep Transaction 9f3b024ed86e0ea8747df79c1e2eeda99f159566a4eb54b6f0e94818ff1b0094 confirmed at blockheight: 364
2025-07-25T11:13:47.578584562+00:00 INFO coinswap::wallet::api - Successfully swept incoming swap coin, txid: 9f3b024ed86e0ea8747df79c1e2eeda99f159566a4eb54b6f0e94818ff1b0094
2025-07-25T11:13:47.579373810+00:00 INFO coinswap::wallet::api - Successfully removed incoming swaps coins
2025-07-25T11:13:47.582942955+00:00 INFO coinswap::wallet::api - Sweeping incoming swap coin faca6380ecc85b562b5f3874528e08db2f26db0d415d4b1e32d1b7bd981897b9 to internal address bcrt1q9p0era9q828m5ta75tlfxfwen04fe27zzxprsq
2025-07-25T11:13:47.583199777+00:00 INFO coinswap::wallet::spend - Fee: 276 sats
2025-07-25T11:13:47.587972285+00:00 INFO coinswap::wallet::spend - Created Funding tx, txid: 7e0e1bd800a7b27809cb8420c94ce2b3e5c64b4e4617f9401456bc7f35c8ed86 | Size: 137 vB | Fee: 276 sats | Feerate: 2.01 sat/vB
2025-07-25T11:13:47.596666069+00:00 INFO coinswap::wallet::api - Sweep Transaction 7e0e1bd800a7b27809cb8420c94ce2b3e5c64b4e4617f9401456bc7f35c8ed86 seen in mempool, waiting for confirmation.
2025-07-25T11:13:47.596701455+00:00 INFO coinswap::wallet::api - Next sync in 10 secs
2025-07-25T11:13:48.501590292+00:00 WARN coinswap::taker::api - Failed to connect to maker 127.0.0.1:6102 to settle coinswap, reattempting 10 of 10 error=IO(Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })
2025-07-25T11:13:49.501925500+00:00 WARN coinswap::taker::api - Failed to connect to maker 127.0.0.1:6102 to settle coinswap, reattempting 11 of 10 error=IO(Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })
2025-07-25T11:13:49.502675265+00:00 WARN coinswap::taker::api - Failed to connect to maker 127.0.0.1:6102 to settle coinswap, reattempt limit exceeded
2025-07-25T11:13:49.504201734+00:00 ERROR coinswap::taker::api - Swap Settlement Failed : IO(Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })
2025-07-25T11:13:49.504630818+00:00 WARN coinswap::taker::api - Starting recovery from existing swap
2025-07-25T11:13:49.506578406+00:00 INFO coinswap::wallet::api - Unfinished incoming txids: [196952dbaf7d32a5e2fb1bb18ec276f1f3f7ca25a66664d685482cceb1613669, 078d9e9280ff52bd2c610f49540e380007f0e6fb4ad3f71d8e6f349416ebd56f, deb52a8b2ebd56e08a69c768a5caf20930a4607352b7ebea85e13ba19eebc62b]
2025-07-25T11:13:49.506626155+00:00 INFO coinswap::wallet::api - Unfinished outgoing txids: [76792723dd796cb7b97fa809b29a9d759a4528666968ea4f07feda84c32479a7, ff3506e4feb18ae75af7d7f0b5e20f52316cb0009a6c6c8268930961640d8c65, b3b6c416355c0cb833ca5716fc8b7115a3d9958fc75cf64158c05902911ecf55]
2025-07-25T11:13:49.524974071+00:00 INFO coinswap::taker::api - Broadcasting Incoming Contract. Removing from wallet. Txid : 196952dbaf7d32a5e2fb1bb18ec276f1f3f7ca25a66664d685482cceb1613669
2025-07-25T11:13:49.525177863+00:00 INFO coinswap::taker::api - Incoming Swapcoin removed from wallet, Txid: 196952dbaf7d32a5e2fb1bb18ec276f1f3f7ca25a66664d685482cceb1613669
2025-07-25T11:13:49.531443187+00:00 INFO coinswap::taker::api - Broadcasting Incoming Contract. Removing from wallet. Txid : 078d9e9280ff52bd2c610f49540e380007f0e6fb4ad3f71d8e6f349416ebd56f
2025-07-25T11:13:49.531485296+00:00 INFO coinswap::taker::api - Incoming Swapcoin removed from wallet, Txid: 078d9e9280ff52bd2c610f49540e380007f0e6fb4ad3f71d8e6f349416ebd56f
2025-07-25T11:13:49.538019675+00:00 INFO coinswap::taker::api - Broadcasting Incoming Contract. Removing from wallet. Txid : deb52a8b2ebd56e08a69c768a5caf20930a4607352b7ebea85e13ba19eebc62b
2025-07-25T11:13:49.538064159+00:00 INFO coinswap::taker::api - Incoming Swapcoin removed from wallet, Txid: deb52a8b2ebd56e08a69c768a5caf20930a4607352b7ebea85e13ba19eebc62b

thread 'abort3_case3_close_at_hash_preimage_handover' panicked at tests/abort3_case3.rs:115:36:
called `Result::unwrap()` on an `Err` value: Wallet(Rpc(JsonRpc(Rpc(RpcError { code: -25, message: "bad-txns-inputs-missingorspent", data: None }))))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2025-07-25T11:13:49.624907828+00:00 INFO coinswap::taker::api - Shutting down taker.
2025-07-25T11:13:49.628932125+00:00 INFO coinswap::taker::api - offerbook data saved to disk.
2025-07-25T11:13:49.630584019+00:00 INFO coinswap::taker::api - Wallet data saved to disk.
test abort3_case3_close_at_hash_preimage_handover ... FAILED
```

Needs to be investigated and fix the root cause.

### PR DESCRIPTION
**Pull request by stark-3k**
fixes #564

### CODE REVIEW

File: src/taker/api.rs [hunk 1]
```diff
@@ -462,17 +462,17 @@ impl Taker {
         }
 
         match self.settle_all_swaps() {
-            Ok(_) => (),
+            Ok(_) => {
+                log::info!("Initializing Sync and Save.");
```
Comment (mojoX911) [inline src/taker/api.rs]:
```suggestion
                log::info!("Swaps settled successfully. Sweeping the coins and reseting everything.");
```

File: src/taker/api.rs [hunk 2]
```diff
@@ -1794,14 +1794,27 @@ impl Taker {
...
+        let (unfinished_incomings, _) = self.wallet.find_unfinished_swapcoins();
+
+        if unfinished_incomings.is_empty() {
+            log::info!(
+                "No unfinished swapcoins detected, sweeping completed incoming swap coins..."
+            );
 
-        let swept_txids = self.wallet.sweep_incoming_swapcoins(MIN_FEE_RATE)?;
-        if !swept_txids.is_empty() {
+            let swept_txids = self.wallet.sweep_incoming_swapcoins(MIN_FEE_RATE)?;
```
Comment (mojoX911) [inline src/taker/api.rs]: Take sweeping out of save and reset and call it at the site.

**Review by mojoX911 — CHANGES_REQUESTED** [review]
