### PR TITLE
fix: Limit the fidelity timelock b/w 3-6months in maker config

### LINKED ISSUE #664: [fiddelity] Limit for maximum and minumum timelock
For security purposes, the fidelity bond timelock should be set to a minimum of 3 months and a maximum of 6 months. 

This should be configurable at the maker config.toml.

Redeeming the fidelity bond API in the wallet should be made private.

### PR DESCRIPTION
**Pull request by 0xEgao**
fixes #664
Note-: The need of moving the `verify_fidelity_checks` to `wallet/fidelity` module is because it calls `fidelity_redeemscript` which is a private api now.

### CODE REVIEW

File: src/maker/config.rs [hunk 1]
```diff
@@ -66,6 +71,26 @@ impl Default for MakerConfig {
...
+        log::warn!(
+            "fidelity_timelock too high ({} blocks). Clamping to maximum allowed: {} blocks",
+            timelock,
+            MAX_FIDELITY_TIMELOCK
+        );
+        MAX_FIDELITY_TIMELOCK
+    } else {
+        timelock
+    }
+}
```
Comment (stark-3k) [inline src/maker/config.rs:87]: We don't want to automatically assign timelocks if someone enters an out of range timelock, we just don't create a fidelity and warn them in the logs about the accepted range and that fidelity does not exist, can't proceed.

File: src/wallet/fidelity.rs [hunk 2]
```diff
@@ -65,6 +65,68 @@ pub(crate) fn fidelity_redeemscript(lock_time: &LockTime, pubkey: &PublicKey) ->
         .into_script()
 }
 
+/// Verifies a fidelity bond by checking timelock validity,
+/// certificate integrity, redeem script existence, and ECDSA signature correctness.
+pub(crate) fn verify_fidelity_checks(
```
Comment (stark-3k) [inline src/wallet/fidelity.rs:84]: also verify the fidelity range here

Comment (0xEgao) [reply src/wallet/fidelity.rs:84]: Done

File: src/maker/config.rs (hunk 1 above)
Comment (0xEgao) [reply src/maker/config.rs:87]: Done

**Comment by 0xEgao** [comment]
> ## Code review
> I found one CLAUDE.md compliance issue that should be addressed.
> 
> ### Issue: Feature flag pattern violation in fidelity timelock validation
> **Location:** src/wallet/fidelity.rs:79-96
> 
> The fidelity timelock validation is skipped entirely during integration tests using `cfg!(not(feature = "integration-test"))`, but [CLAUDE.md](https://github.com/citadel-tech/coinswap/blob/1ee7548cac56fcc49abd7062dbc536783d07346e/CLAUDE.md#L198-L203) requires providing test-specific constant values instead:
> 
> > When adding new timeouts/constants, use `#[cfg(feature = "integration-test")]` to provide test-specific values.
> 
> **Problem:** The current implementation completely bypasses validation logic in tests, which means the validation code itself is never tested.
> 
> **Solution:** The constants should have conditional values like this pattern used elsewhere in the codebase:
> 
> ```rust
> #[cfg(feature = "integration-test")]
> pub const MIN_FIDELITY_TIMELOCK: u32 = 100; // Shorter for tests
> #[cfg(feature = "integration-test")]
> pub const MAX_FIDELITY_TIMELOCK: u32 = 26_000; // Test value
> 
> #[cfg(not(feature = "integration-test"))]
> pub const MIN_FIDELITY_TIMELOCK: u32 = 12_960; // 3 months
> #[cfg(not(feature = "integration-test"))]
> pub const MAX_FIDELITY_TIMELOCK: u32 = 25_920; // 6 months
> ```
> 
> Then the validation code at lines 79-96 should run unconditionally (remove the `if cfg!(not(feature = "integration-test"))` wrapper), ensuring validation logic is exercised during testing with appropriate test values.
> 
> All other aspects of the PR look good - no bugs or logic issues detected.

Done

**Review by mojoX911 — CHANGES_REQUESTED** [review]
An IT and this is good to go.

File: src/maker/server2.rs [hunk 3]
```diff
@@ -301,12 +301,17 @@ fn setup_fidelity_bond_taproot(
...
-    } else {
-        LockTime::from_height(maker.config.fidelity_timelock + current_height)
-            .map_err(WalletError::Locktime)?
+    #[cfg(feature = "integration-test")]
+    let locktime = {
+        if maker.behavior == TaprootMakerBehavior::InvalidFidelityTimelock {
+            LockTime::from_height(current_height + 500).map_err(WalletError::Locktime)?
+        } else {
+            LockTime::from_height(current_height + 950).map_err(WalletError::Locktime)?
+        }
```
Comment (mojoX911) [inline src/maker/server2.rs:215]: This is okay. But this isn't fully capturing the whole of the workflow, where the user changes the config with an invalid bond locktime and tries to restart the maker.

Then the fidelity check in Maker Inti will kick in, showing the error. That can't be simulated by a behavior like this.

You have to simulate from config file generation, restart the maker on that config file and then assert that checks are hit properly via the logs.

In general, when adding special behavior like this, we need to be careful. Behavior changes will only affect the takers, not the maker code in any way. Behaviors are there to skip certain maker internal logic. As a result, they can't be used to test maker's internal logic itself.

File: tests/fidelity_timelock_violation.rs [hunk 4]
```diff
@@ -0,0 +1,156 @@
...
+    };
+
+    // Attempt the swap - it will fail when taker discovers that maker's fidelity bond doesn't lie in the accepted fidelity_timelock limit via offerbook sync.
+    match taproot_taker.do_coinswap(swap_params) {
+        Ok(Some(_report)) => {
+            panic!("Swap should have failed due to less makers available than required, closing connection, but succeeded with report!");
+        }
+        Ok(None) => {
+            info!("✅ Taproot coinswap triggered recovery as expected (Ok(None))");
+        }
```
Comment (mojoX911) [inline tests/fidelity_timelock_violation.rs]: We should panic here too? In no case there would be a recovery situation.. If it does, the test should scream.

File: tests/fidelity_timelock_violation.rs [hunk 5]
```diff
@@ -0,0 +1,156 @@
...
+    }
+
+    taproot_taker.get_wallet_mut().sync_and_save().unwrap();
+    let taker_balances_after = taproot_taker.get_wallet().get_balances().unwrap();
+    info!(
+         "📊 Taproot Taker balance after failed swap: Regular: {}, Contract: {}, Spendable: {}, Swap: {}",
+        taker_balances_after.regular,
+        taker_balances_after.contract,
+        taker_balances_after.spendable,
+        taker_balances_after.swap,
```
Comment (mojoX911) [inline tests/fidelity_timelock_violation.rs]: Balance check is redundant here. Swap will never go through.  So can be skipped.

Comment (mojoX911) [reply tests/fidelity_timelock_violation.rs]: Instead lets add the maker init test here. 
- Stop the maker.
- Change the maker's config file bond locktime value.
- Restart the maker.
- Assert that the maker doesn't start, and error with the right error message.

You can do this without testframeowkr init, by directly calling on the maker struct.

Comment (0xEgao) [reply tests/fidelity_timelock_violation.rs]: Done

File: tests/fidelity_timelock_violation.rs (hunk 4 above)
Comment (0xEgao) [reply tests/fidelity_timelock_violation.rs]: Yeah a panic here will be good, added that

File: src/maker/config.rs [hunk 6]
```diff
@@ -47,7 +50,7 @@ impl Default for MakerConfig {
     fn default() -> Self {
         let (fidelity_amount, fidelity_timelock, base_fee, amount_relative_fee_pct) =
             if cfg!(feature = "integration-test") {
-                (5_000_000, 26_000, 1000, 2.50) // Test values
+                (5_000_000, MAX_FIDELITY_TIMELOCK, 1000, 2.50) // Test values
             } else {
                 (50_000, 13104, 100, 0.1) // Production values
```
Comment (mojoX911) [inline src/maker/config.rs]: Production value also needs to be changed here.

File: src/maker/config.rs [hunk 7]
```diff
@@ -66,6 +69,22 @@ impl Default for MakerConfig {
         }
     }
 }
+/// Ensure fidelity timelock lies in the allowed range (3–6 months)
+fn validate_fidelity_timelock(timelock: u32) -> io::Result<u32> {
```
Comment (mojoX911) [inline src/maker/config.rs]: This is not an IO error. This should be `WalletError::FidelityError`.

File: src/maker/config.rs [hunk 8]
```diff
@@ -252,4 +274,13 @@ mod tests {
...
         assert_eq!(config, MakerConfig::default());
     }
+
+    #[test]
+    fn fidelity_timelock_out_of_range_fails() {
+        let contents = r#"fidelity_timelock = 500"#; // below minimum timelock
+        let path = create_temp_config(contents, "invalid_timelock.toml");
+        let result = MakerConfig::new(Some(&path));
+        remove_temp_config(&path);
+        assert!(result.is_err());
```
Comment (mojoX911) [inline src/maker/config.rs]: Assert the exact error.

File: src/maker/config.rs (hunk 7 above)
Comment (mojoX911) [reply src/maker/config.rs]: Add a new variant in that error.

File: src/wallet/fidelity.rs [hunk 9]
```diff
@@ -65,6 +77,86 @@ pub(crate) fn fidelity_redeemscript(lock_time: &LockTime, pubkey: &PublicKey) ->
...
+    let lock_time = LockTime::from_height(current_height as u32)?;
+    if lock_time > proof.bond.lock_time {
+        return Err(FidelityError::BondLocktimeExpired.into());
+    }
+
+    // Verify certificate hash
+    let expected_cert_hash = proof
+        .bond
+        .generate_cert_hash(addr)
+        .expect("Bond is not yet confirmed");
```
Comment (mojoX911) [inline src/wallet/fidelity.rs]: Lets remove this expect. No reason to panic here. 

Instead, it should throw an error `BondUnconfirmed`.

File: src/wallet/fidelity.rs [hunk 10]
```diff
@@ -65,6 +77,86 @@ pub(crate) fn fidelity_redeemscript(lock_time: &LockTime, pubkey: &PublicKey) ->
...
+
+    let mut all_failed = true;
+
+    for network in networks {
+        // Validate redeem script and corresponding address
+        let fidelity_redeem_script =
+            fidelity_redeemscript(&proof.bond.lock_time, &proof.bond.pubkey);
+        let expected_address = Address::p2wsh(fidelity_redeem_script.as_script(), network);
+
+        let derived_script_pubkey = expected_address.script_pubkey();
```
Comment (mojoX911) [inline src/wallet/fidelity.rs:138]: There is a problem here. Someone can pass in a testnet fidelity, when a mainnet fidelity is expected, and this logic will still pass it. 

We should correlate this to the wallet network variable, in which the current wallet is running and only validate against that network. We are also losing some compute cycles here unnecessarily. 

Can be done in a follow-up PR.

File: src/wallet/fidelity.rs (hunk 9 above)
Comment (0xEgao) [reply src/wallet/fidelity.rs]: done

File: src/maker/config.rs (hunk 8 above)
Comment (0xEgao) [reply src/maker/config.rs]: done

File: src/maker/config.rs (hunk 7 above)
Comment (0xEgao) [reply src/maker/config.rs]: Done, Added

File: src/wallet/fidelity.rs (hunk 10 above)
Comment (0xEgao) [reply src/wallet/fidelity.rs:138]: Cool i will take this up in a follow up pr

**Review by mojoX911 — APPROVED** [review]
Ack
