### PR TITLE
fix: prevent stale fidelity bond broadcast on nostr

### LINKED ISSUE #702: Watcher keeps broadcasting old fidelity
For v1 makers, even though we have automatic fidelity renewal, the watcher captures the old fidelity and continually broadcasts it to nostr. This is problematic because takers will keep seeing this old expired fidelity and deny swapping with them. We want the watcher to always broadcast the outpoint of the latest fidelity bond.

### PR DESCRIPTION
**Pull request by 0xEgao**
Fixes #702
`Note`-: Though the issue mentions that this problem is with v1 makers, but i think the current logic could have caused same problem with v2 makers. So I have changed both `maker/servers` accordingly.

## Summary by CodeRabbit

* **Refactor**
  * Broadcasts now read the latest fidelity proof from shared state at send time, performing periodic checks and logging when fidelity is missing or unreadable; initial one-off send removed.
* **Breaking Change**
  * Public broadcast task API simplified to a single-parameter form (breaking change); callers must adapt to the new signature and state-driven behavior.

### CODE REVIEW

File: src/maker/server.rs [hunk 1]
```diff
@@ -87,28 +87,44 @@ fn manage_fidelity_bonds(
...
+    match fidelity {
+        Some(proof) => {
+            if let Err(e) = broadcast_bond_on_nostr(proof) {
+                log::warn!("{context} nostr broadcast failed: {:?}", e);
+            }
+        }
+        None => {
+            log::warn!("No fidelity proof available for {context} nostr broadcast");
+        }
+    }
```
Comment (stark-3k) [inline src/maker/server.rs]: instead of adding a new function, we can simply just get the latest fidelity and use the existing `broadcast_bond_on_nostr` in the `spawn_nostr_broadcast_task` itself

Comment (0xEgao) [reply src/maker/server.rs]: I created a helper fn coz same code of getting the latest fidelity data was repeated twice ,but yeah will revert back to the first commit then.

Comment (stark-3k) [reply src/maker/server.rs]: yeah i see, but i think we should be able to consolidate `spawn_nostr_broadcast_task` to have a single call to broadcast the fidelity bond in a loop

Comment (0xEgao) [reply src/maker/server.rs]: Done

File: src/maker/server.rs [hunk 2]
```diff
@@ -87,47 +87,46 @@ fn manage_fidelity_bonds(
...
-
     let handle = thread::Builder::new()
         .name("nostr-event-thread".to_string())
         .spawn(move || {
-            if let Err(e) = broadcast_bond_on_nostr(fidelity.clone()) {
-                log::warn!("initial nostr broadcast failed: {:?}", e);
-            }
-
             let interval = Duration::from_secs(30 * 60);
-            let tick = Duration::from_secs(2);
```
Comment (stark-3k) [inline src/maker/server.rs:113]: we need this tick interval to check the shutdown flag every 2 seconds instead of 30 minutes or the thread won't terminate

Comment (mojoX911) [reply src/maker/server.rs:113]: Should be the `HEART_BEAT_INTERVAL` global const. That allows us to keep all ticks consistent across the threads.

Comment (0xEgao) [reply src/maker/server.rs:113]: By mistake did a 30min thread sleep, changed to `HEART_BEAT_INTERVAL`
