### PR TITLE
offerbook improvisation

### LINKED ISSUE #720: Improve Offerbook Syncing
The current offerbook syncing logic can be significantly optimized. Some basic failure cases can be handled well. Some smarter checkup logic can improve sync waiting time a lot.

Below is a list (not exhaustive) of major things that can be improved.

- Add a backup nost relay. If nostr.lol fails, instead of failing the sync, it should connect to the backup relay to fetch offers.
- Timestamp each maker's offer update. Instead of downloading the offer from everybody at sync, only download for those makers who haven't been updated in the last 30 minutes.
- Reduce preferences to connect to known unresponsive makers. Tor connections are costly. We can use some timeout increment for unresponsive makers. For every dead maker, increment the next connection checking time by 30 mins. That way, for makers who are dead for a long time, they won't be checked for connection at every sync.

This and many other smaller improvements can be made.

### PR DESCRIPTION
**Pull request by 0xEgao**
Fixes #720

## Summary by CodeRabbit

* **New Features**
  * REST-based Bitcoin backend support for read-only endpoints.
  * Time-aware offer tracking: records last-success and next-check timestamps and persists offerbook updates.

* **Improvements**
  * Intelligent polling that skips recently-updated offers and enforces exponential backoff for unresponsive makers.
  * Polling and success/failure handling use current UNIX timestamps for accurate scheduling.
  * Improved HTTP timeout and request handling for more reliable network operations.

* **Documentation**
  * Bitcoin config docs updated to enable REST endpoints.

* **Tests**
  * Added tests for polling/backoff and success handling.

### CODE REVIEW

File: src/taker/offers.rs [hunk 1]
```diff
@@ -361,41 +394,41 @@ impl OfferSyncService {
...
+                    book.mark_failure(addr, now);
                 }
             }
-        }
 
-        self.offerbook.persist()?;
+            // Persist without re-locking (avoid deadlock via OfferBookHandle::persist()).
+            let path = self.offerbook.path.clone();
+            book.write_to_disk(&path)?;
+        }
```
[the remark this answers is not in the document]
Comment (0xEgao) [reply src/taker/offers.rs:427]: Thanks for the suggestion, added `.truncate(true)`

File: src/taker/offers.rs [hunk 2]
```diff
@@ -45,11 +46,23 @@ use crate::{
...
+
+#[cfg(feature = "integration-test")]
+const OFFER_MAX_AGE_BEFORE_REFRESH: Duration = Duration::from_secs(10);
+
+#[cfg(not(feature = "integration-test"))]
+const UNRESPONSIVE_MAKER_BACKOFF_STEP: Duration = Duration::from_secs(30 * 60);
+
+#[cfg(feature = "integration-test")]
+const UNRESPONSIVE_MAKER_BACKOFF_STEP: Duration = Duration::from_secs(10);
+
```
Comment (hulxv) [inline src/taker/offers.rs:65]:
```suggestion
#[cfg(not(feature = "integration-test"))] const SCALE: u64 = 60;
#[cfg(feature = "integration-test")]     const SCALE: u64 = 1;

const OFFER_SYNC_INTERVAL:            Duration = Duration::from_secs(10 * SCALE);
const OFFER_MAX_AGE_BEFORE_REFRESH:   Duration = Duration::from_secs(30 * SCALE);
const UNRESPONSIVE_MAKER_BACKOFF_STEP: Duration = Duration::from_secs(30 * SCALE);
```

why we don't do something like that? I think it's like that is better

File: src/watch_tower/rpc_backend.rs [hunk 3]
```diff
@@ -14,57 +13,106 @@ use crate::{
     },
 };
 
-/// Lightweight wrapper around bitcoind RPC calls used by the watchtower.
+const DEFAULT_HTTP_TIMEOUT_SECS: u64 = 30;
+
+/// Lightweight wrapper around bitcoind REST endpoints used by the watchtower (no longer uses JSON-RPC).
 pub struct BitcoinRpc {
```
Comment (hulxv) [inline src/watch_tower/rpc_backend.rs]: shouldn't be renamed?

**Review by hulxv — CHANGES_REQUESTED** [review]

File: src/watch_tower/rpc_backend.rs (hunk 3 above)
Comment (0xEgao) [reply src/watch_tower/rpc_backend.rs]: Done

File: src/taker/offers.rs (hunk 2 above)
Comment (0xEgao) [reply src/taker/offers.rs:65]: For integration test  `OFFER_MAX_AGE_BEFORE_REFRESH ` and `UNRESPONSIVE_MAKER_BACKOFF_STEP` is lower i.e. 10secs for keeping the test complete in less time. So, tho something like this is better, but still it won't reduce the number of loc.

**Review by mojoX911 — APPROVED** [review]
Nice work. Very clean. Like the way you could add UT for it. 

Ack.
