### PR TITLE
Fix fn handle_private_key_handover

### LINKED ISSUE #628: [Bug] in fn handle_private_key_handover

### PR DESCRIPTION
**Pull request by Godzilla-oss**
Fixes #628 Modified `fn handle_private_key_handover`
- carry the swap `unique_id` through `PrivKeyHandover`
- drop only the finished swap from `ongoing_swap_state`

### CODE REVIEW

File: src/protocol/messages.rs [hunk 1]
```diff
@@ -182,6 +182,7 @@ pub(crate) struct MultisigPrivkey {
 #[derive(Debug, Serialize, Deserialize)]
 pub(crate) struct PrivKeyHandover {
     pub(crate) multisig_privkeys: Vec<MultisigPrivkey>,
+    pub(crate) unique_id: Option<String>,
```
Comment (Wukong247) [inline src/protocol/messages.rs]: Why Option?

Comment (Godzilla-oss) [reply src/protocol/messages.rs]: In the `fn handle_hash_preimage`  
```
Ok(MakerToTakerMessage::RespPrivKeyHandover(PrivKeyHandover {
            multisig_privkeys: swapcoin_private_keys,
            unique_id: None,
        }))
```
where previously it returned only `multisig_privkeys`. So, option to make unique_id:None

Comment (mojoX911) [reply src/protocol/messages.rs]: Add a doc comment here why this field is needed and why its kept as an option.

File: src/maker/handlers.rs [hunk 2]
```diff
@@ -637,10 +638,12 @@ impl Maker {
                 key: outgoing_swapcoin.my_privkey,
             });
         }
-
+        
+        let unique_id = message.preimage[0..8].to_hex_string(Case::Lower);
         self.wallet.write()?.save_to_disk()?;
         Ok(MakerToTakerMessage::RespPrivKeyHandover(PrivKeyHandover {
             multisig_privkeys: swapcoin_private_keys,
+            id: unique_id,
```
Comment (mojoX911) [inline src/maker/handlers.rs:646]: Unique id is not needed for the taker. So it can just be an empty string.

Comment (bit-aloo) [reply src/maker/handlers.rs:646]: Just to be consistent, I guess its ok, though taker might not use it.

Comment (mojoX911) [reply src/maker/handlers.rs:646]: No strong opinion. Okay either way.

**Review by Wukong247 — COMMENTED** [review]
@Godzilla-oss Can you format the code?

File: src/protocol/messages.rs (hunk 1 above)
Comment (Godzilla-oss) [reply src/protocol/messages.rs]: Fixed in 0b9ac9dd052d2a5d07006904f06cbab40f45b52b
